// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35XDLSqGlWg54DVLxp50UwnE41LasIkA',
    appId: '1:275569710088:web:72e0126bbdde9756eaadbd',
    messagingSenderId: '275569710088',
    projectId: 'carrenting-77d97',
    authDomain: 'carrenting-77d97.firebaseapp.com',
    storageBucket: 'carrenting-77d97.firebasestorage.app',
    measurementId: 'G-MXRWM5BW11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6IQNK0GmZsrlpJVDpDvQUaJtREhfTM0',
    appId: '1:275569710088:android:08621b5ac3db40adeaadbd',
    messagingSenderId: '275569710088',
    projectId: 'carrenting-77d97',
    storageBucket: 'carrenting-77d97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJ3p6qd45lSy4j1tNPV-BGwRuoKBwUAg',
    appId: '1:275569710088:ios:95865921362b6ec6eaadbd',
    messagingSenderId: '275569710088',
    projectId: 'carrenting-77d97',
    storageBucket: 'carrenting-77d97.firebasestorage.app',
    iosBundleId: 'com.example.carRentingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJ3p6qd45lSy4j1tNPV-BGwRuoKBwUAg',
    appId: '1:275569710088:ios:95865921362b6ec6eaadbd',
    messagingSenderId: '275569710088',
    projectId: 'carrenting-77d97',
    storageBucket: 'carrenting-77d97.firebasestorage.app',
    iosBundleId: 'com.example.carRentingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB35XDLSqGlWg54DVLxp50UwnE41LasIkA',
    appId: '1:275569710088:web:55d418bc2fc1114aeaadbd',
    messagingSenderId: '275569710088',
    projectId: 'carrenting-77d97',
    authDomain: 'carrenting-77d97.firebaseapp.com',
    storageBucket: 'carrenting-77d97.firebasestorage.app',
    measurementId: 'G-THVJDQHVMK',
  );
}
